[opener]
image_viewer = [
    { run = 'feh --scale-down --auto-zoom --image-bg "#1E1E2E" "$@"', orphan = true, desc = "feh" }
]
audio_player = [
    { run = 'deadbeef "$@"', orphan = true, desc = "DeaDBeeF" }
]
video_player = [
    { run = 'vlc "$@"', orphan = true, desc = "VLC" }
]
sioyek = [
    { run = 'sioyek "$@"', orphan = true, desc = "Open in Sioyek" }
]
excel = [
    { run = 'localc "$@"', orphan = true, desc = "Open in LibreOffice Calc" }
]
neovim = [
    { run = 'nvim "$@"', orphan = true, desc = "Open in Neovim" }
]

[open]
prepend_rules = [
    { mime = "image/*", use = "image_viewer" },
    { mime = "audio/*", use = "audio_player" },
    { mime = "video/*", use = "video_player" },
    { mime = "application/pdf", use = "sioyek" },
    { mime = "*.xlsx", use = "excel" },
    { mime = "*.xls",  use = "excel" },
    { mime = "*.csv",  use = "excel"},
    { mime = "*.history", use = "neovim" }
]
